apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KAFKA_SERVICE_HOST
              value: demo-cluster-kafka-bootstrap
            - name: KAFKA_SERVICE_PORT
              value: '9091'
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=openshift"

